branches:
  only: master
  except: master
  publish: True
releases: True
domains:
- schema:
    url: https://github.com/hugdru/schemas/blob/master/big_data-schema.yaml
  data:
    Scalability:
      Scalable Distribution Architecture: [horizontal partitioning of database, horizontal partitioning and replication]
      Scaling Out - Adding Data Storage Capacity: manual data rebalancing
      Request Load Balancing: uses HTTP-based load balancers
      Granularity of Write Locks: no locks - single threaded execution
      Scalable Request Processing Architecture: based on an external load balancer
    Consistency:
      Object Level Atomic Updates: supported
      ACID Transactions: lightweight transactions
      Distributed Transactions: not supported
      Durable Writes: supported
      Quorum Reads and Writes: not supported
      Number of Replicas to Read: master-slave
      Number of Replicas to Write: specified in the database configuration
      Writes with Unavailable Replicas: no rollback: write returns replication error
      Read from Master Only: specified in the client
      Resolving Write Conflicts: not applicable: master-slave
    Query Language:
      API-based: supported
      Declarative Query Language: not suppported
      REST/HTTP-based Queries: not suppported
      Languages Supported: [Java, C#, Python, C/C++, Perl, PHP, Ruby, Scala, Erlang, Javascript]
      Cursor-based Queries: supported
      JOIN-style queries: not suppported
      Complex Data Types: lists, maps, sets
      Restrict Query Result Set Size: supported
      Key Matching Options: [exact, partial match, wildcards]
      Sort Options: [ascending, descending]
      Triggers: not supported
      Data Object Expiry: supported
    Data Model:
      Data model: Key-Value
      Fixed Schema: not required
      Opaque Data Objects: not required
      Hierarchical Data Objects: not supported
      Automatically allocated Primary Key: not supported
      Composite Keys: not supported
      Secondary Indexes: not supported
      Query by Key Ranges: supported
      Query by Partial Keys: supported
      Query by Non-key Values: not supported
      Map Reduce API: not supported
      Indexed Text Search: not supported
    Data Replication:
      Replication Architecture: master-slave
      Replication for Backup: not suppported
      Replication across Data Centers: supported only by standard replication mechanisms
      Replica Writes: [to master replica only, to any replica]
      Replica Reads: from any replica
      Read Repair: not relevant
      Automatic Replica Failure Detection: supported
      Automatic Failover: supported
      Automatic New Master Election after Failure: supported
      Replica Recovery and Resynchronization: supported - automatic
    Data Distribution:
      Data Distribution Architecture: [master-single slave, master-multiple slaves]
      Data Distribution Method: hash key
      Automatic Data Rebalancing: administrative rebalancing tools
      Physical Data Distribution: [single cluster, multiple data centers]
      Query Architecture: direct shard connection only (resolved in client)
      Queries using Non-Shard Key Value: not supported
      Merging Query Results from Multiple Shards: not supported
    Security:
      Client Authentication: custom user/password
      Server authentication: shared keyfile
      Credential Store: external file
      Role Based Security: not supported
      Security Role Options: not supported
      Scope of Roles: database
      Database Encryption: not supported
      Logging: no logging
    Admin:
      Configuration Files: single
      Node command line access: non-authenticated
      Node addition/removal: centralized tool
      Cluster monitoring: real-time
      Dump database configuration: supported
      Database object count: supported
      Physical storage usage: supported
